name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install QuickFIX C++ library
      run: |
        sudo apt-get update
        sudo apt-get install -y libquickfix-dev
    
    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4'
        cabal-version: '3.10'
    
    - name: Cache Cabal packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-cabal-
    
    - name: Update Cabal package list
      run: cabal update
    
    - name: Build
      run: cabal build
